import type { Config } from "tailwindcss";

export default {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {},
    },
  },
  plugins: [],
  safelist: [
    "w-[800px]",
    "border-2",
    'grid-cols-1',
    'grid-cols-2',
    'grid-cols-3',
    'grid-cols-4',
    'grid-cols-5',
    'grid-cols-6',
    'grid-cols-7',
    'grid-cols-8',
    'grid-cols-9',
    'grid-cols-10',
    'grid-cols-11',
    'grid-cols-12',
    'grid-cols-13',
    'grid-cols-14',
    'grid-cols-15',
    'grid-cols-16',
    'grid-cols-17',
    'grid-cols-18',
    'grid-cols-19',
    'grid-cols-20',
    'grid-cols-21',
    'grid-cols-22',
    'grid-cols-23',
    'grid-cols-24',
    'grid-cols-25',
    'grid-cols-26',
    'grid-cols-27',
    'grid-cols-28',
    'grid-cols-29',
    'grid-cols-30',
    'grid-cols-31',
    'grid-cols-32',
    'grid-cols-33',
    'grid-cols-34',
    'grid-cols-35',
    'grid-cols-36',
    'grid-cols-37',
    'grid-cols-38',
    'grid-cols-39',
    'grid-cols-40',
    'grid-cols-41',
  ]
} satisfies Config;
